sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
install:
  - npm install
script:
  - npm run cover
  - npm run coverage:check
  - npm run build
after_success:
  - npm run coverage:report
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
